wandb_version: 1

path:
  desc: null
  value: genres_mod.parquet
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709343912.919648
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
